//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Labours = new HashSet<Labour>();
            this.Parts = new HashSet<Part>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int JobId { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string Km { get; set; }
        public int VehicleId { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
        public virtual ICollection<Labour> Labours { get; set; }
        public virtual ICollection<Part> Parts { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
