//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labour
    {
        public int LabourId { get; set; }
        public string Time { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int JobId { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
