//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaintenanceTrackerEntities : DbContext
    {
        public MaintenanceTrackerEntities()
            : base("name=MaintenanceTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Labour> Labours { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
    }
}
