//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int PartId { get; set; }
        public int JobId { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
